# Generated by Django 6.1.1 on 2026-09-26 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="To'liq ismi"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="quran/authors/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "birth_year",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tug'ilgan yil"
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="Haqida")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("uz", "O'zbekcha"),
                            ("ar", "Arabcha"),
                            ("ru", "Ruscha"),
                            ("en", "Inglizcha"),
                        ],
                        default="uz",
                        max_length=5,
                        verbose_name="Til",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muallif",
                "verbose_name_plural": "Mualliflar",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["language"], name="quran_autho_languag_d80060_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuranBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Sarlavha")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("uz", "O'zbekcha"),
                            ("ar", "Arabcha"),
                            ("ru", "Ruscha"),
                            ("en", "Inglizcha"),
                        ],
                        max_length=5,
                        verbose_name="Til",
                    ),
                ),
                (
                    "pdf",
                    models.FileField(upload_to="quran/books/", verbose_name="PDF fayl"),
                ),
                (
                    "can_read_online",
                    models.BooleanField(
                        default=False, verbose_name="Online o'qish mumkin"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Qur'on kitobi",
                "verbose_name_plural": "Qur'on kitoblari",
                "ordering": ["language"],
                "indexes": [
                    models.Index(
                        fields=["language"], name="quran_quran_languag_ec8466_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Sura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        db_index=True, unique=True, verbose_name="Sura raqami"
                    ),
                ),
                (
                    "name_arabic",
                    models.CharField(max_length=200, verbose_name="Arabcha nomi"),
                ),
                (
                    "name_uzbek",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="O'zbekcha nomi"
                    ),
                ),
                (
                    "name_english",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Inglizcha nomi"
                    ),
                ),
                (
                    "name_russian",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ruscha nomi"
                    ),
                ),
                (
                    "total_ayahs",
                    models.PositiveIntegerField(default=0, verbose_name="Jami oyatlar"),
                ),
                (
                    "revelation_place",
                    models.CharField(
                        blank=True,
                        help_text="Makka yoki Madina",
                        max_length=100,
                        null=True,
                        verbose_name="Nozil bo'lgan joy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sura",
                "verbose_name_plural": "Suralar",
                "ordering": ["number"],
                "indexes": [
                    models.Index(
                        fields=["number"], name="quran_sura_number_17c025_idx"
                    ),
                    models.Index(
                        fields=["name_arabic"], name="quran_sura_name_ar_4e2e77_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Ayah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="Oyat raqami"
                    ),
                ),
                ("text_arabic", models.TextField(verbose_name="Arabcha matn")),
                (
                    "text_uzbek",
                    models.TextField(blank=True, verbose_name="O'zbekcha tarjima"),
                ),
                (
                    "text_russian",
                    models.TextField(blank=True, verbose_name="Ruscha tarjima"),
                ),
                (
                    "text_english",
                    models.TextField(blank=True, verbose_name="Inglizcha tarjima"),
                ),
                (
                    "audio_arabic",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="quran/audio/arabic/",
                        verbose_name="Arabcha audio",
                    ),
                ),
                (
                    "audio_uzbek",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="quran/audio/uzbek/",
                        verbose_name="O'zbekcha audio",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ayahs",
                        to="quran.author",
                        verbose_name="Tarjimon",
                    ),
                ),
                (
                    "sura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ayahs",
                        to="quran.sura",
                        verbose_name="Sura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oyat",
                "verbose_name_plural": "Oyatlar",
                "ordering": ["sura__number", "number"],
                "indexes": [
                    models.Index(
                        fields=["sura", "number"], name="quran_ayah_sura_id_0d854d_idx"
                    ),
                    models.Index(
                        fields=["number"], name="quran_ayah_number_83bcf6_idx"
                    ),
                ],
                "unique_together": {("sura", "number")},
            },
        ),
    ]
