# Generated by Django 5.0.2 on 2024-02-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Quran', max_length=150)),
                ('pdf', models.FileField(upload_to='quran/books/')),
                ('online_read', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Quran',
                'verbose_name_plural': 'Quran',
            },
        ),
    ]
