# Generated by Django 5.0.2 on 2024-02-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran_uz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(upload_to='quran/uz/author/image/'),
        ),
        migrations.AlterField(
            model_name='oyat',
            name='audio',
            field=models.FileField(upload_to='quran/uz/audio/'),
        ),
    ]
