# Generated by Django 5.0.2 on 2024-02-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran_uz', '0002_alter_author_profile_image_alter_oyat_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sura',
            name='yozilgan_joyi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
